// <auto-generated />
namespace CreativeCollab_UberDealership.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class cars2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cars2));
        
        string IMigrationMetadata.Id
        {
            get { return "202308010140324_cars2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
